// This file is auto-generated by the Supabase CLI
// See: https://supabase.com/docs/reference/javascript/generating-types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      gym_campaign_totals: {
        Row: {
          id: number
          total_raised_cents: number
          total_backers: number
          last_updated_at: string
        }
        Insert: {
          id?: number
          total_raised_cents: number
          total_backers: number
          last_updated_at?: string
        }
        Update: {
          id?: number
          total_raised_cents?: number
          total_backers?: number
          last_updated_at?: string
        }
      }
      // Add other tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      increment_gym_campaign: {
        Args: {
          p_amount_cents: number
        }
        Returns: void
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
